import Status from './Status';
import React, {useState} from 'react';
import {ArrowUpRight, Box, LayoutDashboard, Building2, Zap, Package, CloudSun, ChartNoAxesCombined, FlaskConical, ArrowRight, Bell, Wind, Thermometer, BatteryCharging, Fuel} from 'lucide-react';
import SubsystemTabs from '../SubsystemTabs';
import TelemetryCharts from '../TelemetryCharts';
import MlDiagnosticsCard from '../MlDiagnosticsCard';
import IncidentSimulationPanel from '../IncidentSimulationPanel';
import {displayNumber as n, systemLabels, incidentLabels, systemState, sectionWarning, weatherWarning} from './data';

const sections=[['overview','Overview',LayoutDashboard],['infrastructure','Infrastructure',Building2],['energy','Energy',Zap],['logistics','Logistics',Package],['environment','Environment',CloudSun],['analysis','Analysis',ChartNoAxesCombined],['exercises','Exercises',FlaskConical]];
const descriptions={infrastructure:'Inspect water, heating, habitat and structural sensor readings.',energy:'Inspect generation and battery backup. Values come from the station simulator.',logistics:'Review fuel endurance and consumption estimates for supply planning.',environment:'Monitor weather conditions and their effect on station operations.',analysis:'Explore historical readings and experimental model outputs.',exercises:'Run a failure scenario, inspect its effects, and restore the simulated station.'};
function Metric({label,value,unit,note,Icon,onClick,warning=false}) {return <button className={`desk-metric ${warning?'is-warning':''}`} onClick={onClick}><span className="desk-metric-label"><Icon size={17}/>{label}<ArrowUpRight size={15}/></span><strong>{value}<small>{unit}</small></strong><span className="desk-muted">{note}</span></button>;}
function Empty({children}){return <p className="desk-empty" role="status">{children}</p>;}

export default function DashboardWorkspace({stationSlug,telemetry,history,onLaunchTwin,onOpenAlerts,onSelectSubsystem,onTriggerIncident,onRestoreNominal,isSimulating,connectionStatus,commandFeedback}) {
 const [section,setSection]=useState('overview');
 const isMaitri=stationSlug==='maitri'; const k=telemetry?.kpis||{};const sim=telemetry?.simulation||{};
 const alerts=telemetry?.alerts||[];const systems=telemetry?.subsystems||[];
 const incident=telemetry?.active_incident; const hasData=Boolean(telemetry); const forecast=telemetry?.fuel_forecast;
 const fuelVolume=systems.find(s=>s.code==='FUEL_STORAGE')?.telemetry_metadata?.current_liters;
 const lastUpdate=telemetry?.timestamp?new Date(telemetry.timestamp).toLocaleTimeString('en-GB',{timeZone:'UTC',hour12:false}):'Awaiting data';
 const warning=Boolean(incident||alerts.length||systems.some(s=>systemState(s,telemetry)!=='Nominal'));
 return <div className="desk-layout">
  <aside className="desk-rail"><span className="desk-eyebrow">STATION WORKSPACE</span><nav aria-label="Station workspace">{sections.map(([id,label,Icon])=><button key={id} aria-current={section===id?'page':undefined} onClick={()=>setSection(id)}><Icon size={18}/>{label}{sectionWarning(id,telemetry)&&<i aria-label={`${label} requires attention`}/>} </button>)}</nav><div className="desk-rail-note"><span className="desk-eyebrow">PROTOTYPE DATA</span><p>Station readings are simulated. Predictions are model estimates.</p><a href="https://sih2026.vuce.in/ps/SIH26060" target="_blank" rel="noreferrer">PS SIH26060 <ArrowUpRight size={13}/></a></div></aside>
  <div className="desk-content">
   <header className="desk-heading"><div><span className="desk-eyebrow">INDIAN ANTARCTIC RESEARCH STATIONS</span><h1>{isMaitri?'Maitri':'Bharati'} <span>/ {sections.find(s=>s[0]===section)[1]}</span></h1><p>{isMaitri?'Schirmacher Oasis · 70.7658° S, 11.7358° E':'Larsemann Hills · 69.4078° S, 76.1872° E'}</p></div><button className="desk-primary" onClick={onLaunchTwin}><Box size={18}/>Open 3D twin<ArrowUpRight size={16}/></button></header>
   <div className="desk-data-line"><Status warning={connectionStatus!=='LIVE'}>{connectionStatus==='LIVE'?'Stream connected':connectionStatus==='CONNECTING'?'Connecting to station':'Reconnecting · polling fallback'}</Status><span>Simulated telemetry</span><span>Received {lastUpdate}{hasData?' UTC':''}</span></div>
   {commandFeedback&&<div className={`desk-feedback ${commandFeedback.error?'is-warning':''}`} role="status">{commandFeedback.text}</div>}
   {!hasData&&<Empty>Waiting for station telemetry. Connection retries automatically; unavailable readings are shown as —.</Empty>}
   {section==='overview'?<>
    <section className={`desk-station-status ${warning?'is-warning':''}`} aria-label="Station status"><div><Status warning={warning}>{!hasData?'Awaiting station status':warning?'Attention required':'No active alerts'}</Status><h2>{incident?incidentLabels[incident]||incident:alerts.length?`${alerts.length} active station alert${alerts.length===1?'':'s'}`:warning?'Some systems require attention':hasData?'Station systems report nominal operation':'Connecting to the station'}</h2><p>{incident?'A simulated exercise is active. Inspect affected systems or restore the station from Exercises.':'Review essential resources below, then open a system for its readings and operating range.'}</p></div><button className="desk-link" onClick={onOpenAlerts}><Bell size={17}/>Review alerts<ArrowRight size={16}/></button></section>
    <div className="desk-metrics"><Metric Icon={Zap} warning={systemState(systems.find(s=>s.code==='POWER_CHP')||{},telemetry)!=='Nominal'} label="Power generation" value={n(k.power_kw)} unit="kW" note="Total electrical output" onClick={()=>setSection('energy')}/><Metric Icon={BatteryCharging} warning={systemState(systems.find(s=>s.code==='BATTERY_STORAGE')||{},telemetry)!=='Nominal'} label="Battery charge" value={n(k.battery_soc)} unit="%" note={`${n(k.battery_autonomy)} h estimated backup`} onClick={()=>onSelectSubsystem('BATTERY_STORAGE')}/><Metric Icon={Fuel} label="Fuel endurance" value={n(k.fuel_days,0)} unit="days" note="Simulator reserve estimate" onClick={()=>setSection('logistics')}/><Metric Icon={Thermometer} warning={systemState(systems.find(s=>s.code===(isMaitri?'WATER_INTAKE':'HVAC_GLYCOL'))||{},telemetry)!=='Nominal'} label={isMaitri?'Water pipeline':'Heating supply'} value={n(k.thermal_temp)} unit="°C" note={isMaitri?'Lake intake pipe temperature':'Glycol supply temperature'} onClick={()=>setSection('infrastructure')}/></div>
    <div className="desk-overview-grid"><section className="desk-panel"><div className="desk-panel-heading"><div><h2>System watch</h2><p>Reported status and sensor coverage</p></div><span className="desk-eyebrow">{systems.length} SYSTEMS</span></div><div className="desk-system-list">{systems.length?systems.map(s=><button key={s.code} onClick={()=>onSelectSubsystem(s.code)}><span><strong>{systemLabels[s.code]||s.name}</strong><small>{s.sensors?.length||0} monitored readings</small></span><Status warning={systemState(s,telemetry)!=='Nominal'}>{systemState(s,telemetry)}</Status><ArrowUpRight size={16}/></button>):<Empty>No system readings received yet.</Empty>}</div></section>
    <div className="desk-overview-side"><section className={`desk-panel ${sectionWarning('environment',telemetry)?'is-warning':''}`}><div className="desk-panel-heading"><div><h2>Outside conditions</h2><p>Simulator weather state</p></div><CloudSun size={23}/></div><div className="desk-weather-values"><span><Thermometer size={17}/><strong className={weatherWarning(telemetry,'temperature')?'desk-danger-value':''}>{n(k.ambient_temp)}<small>°C</small></strong><small>Air temperature</small></span><span><Wind size={17}/><strong className={weatherWarning(telemetry,'wind')?'desk-danger-value':''}>{n(k.wind_speed)}<small>km/h</small></strong><small>Wind speed</small></span></div><p className="desk-muted">{telemetry?.weather_condition||'Weather condition unavailable'}</p><button className="desk-link" onClick={()=>setSection('environment')}>View environment<ArrowRight size={16}/></button></section><section className="desk-twin-invite"><span className="desk-eyebrow">SPATIAL INSPECTION</span><h2>Put these readings<br/>in station context.</h2><p>Explore rooms, equipment, supply routes and the surrounding terrain.</p><button className="desk-link" onClick={onLaunchTwin}>Explore the digital twin<ArrowUpRight size={17}/></button></section></div></div>
   </>:<>
    <div className="desk-section-intro"><h2>{sectionWarning(section,telemetry)&&<i className="desk-alert-dot" aria-label="Section requires attention"/>} {sections.find(s=>s[0]===section)[1]}</h2><p>{descriptions[section]}</p></div>
    {['energy','infrastructure','environment'].includes(section)&&<SubsystemTabs key={`${stationSlug}-${section}`} stationSlug={stationSlug} telemetry={telemetry} onSelectSubsystem={onSelectSubsystem} group={section}/>}
    {section==='environment'&&<section className="desk-panel"><div className="desk-panel-heading"><div><h2>Environmental conditions</h2><p>{telemetry?.weather_condition||'Awaiting weather state'} · Simulator outputs</p></div></div><div className="desk-reading-grid">{[['Air temperature',k.ambient_temp,'°C'],['Wind speed',k.wind_speed,'km/h'],['Wind direction',telemetry?.wind_direction,'°'],['Surface pressure',k.surface_pressure,'hPa'],['Solar radiation',k.solar_radiation,'W/m²'],['Indoor temperature',sim.indoor_temp,'°C']].map(([label,value,unit])=><article className={`desk-reading ${((label==='Air temperature'&&weatherWarning(telemetry,'temperature'))||(label==='Wind speed'&&weatherWarning(telemetry,'wind')))?'is-warning':''}`} key={label}><span className="desk-reading-label">{label}</span><strong>{n(value)}<small>{unit}</small></strong></article>)}</div></section>}
    {section==='environment'&&<div className="desk-note">The simulator applies weather variations and exercise overrides. Weather sync remains available in the header; these readings are not a verified live station sensor feed.</div>}
    {section==='logistics'&&<><div className="desk-metrics desk-metrics-three"><Metric Icon={Fuel} label="Current fuel endurance" value={n(k.fuel_days,0)} unit="days" note="Simulator reserve estimate" onClick={()=>onSelectSubsystem('FUEL_STORAGE')}/><Metric Icon={Package} label="Fuel inventory" value={n(fuelVolume,0)} unit="L" note="Configured tank inventory" onClick={()=>onSelectSubsystem('FUEL_STORAGE')}/><Metric Icon={Zap} label="Fuel consumption" value={n(sim.fuel_burn_rate)} unit="L/h" note="Current simulated burn rate" onClick={()=>onSelectSubsystem('FUEL_STORAGE')}/></div><section className="desk-panel"><div className="desk-panel-heading"><div><h2>Fuel planning outlook</h2><p>Experimental Ridge regression estimate; it may differ from the simulator reserve estimate.</p></div></div>{forecast?<><div className="desk-inline-readings"><span>Next 7 days <strong>{n(forecast.projected_7day_consumption_l,0)} L</strong></span><span>Model endurance <strong>{n(forecast.forecast_autonomy_days)} days</strong></span><span>Predicted burn <strong>{n(forecast.avg_predicted_burn_lh)} L/h</strong></span></div><div className="desk-table-scroll"><table><thead><tr><th>Planning day</th><th>Temperature estimate</th><th>Burn estimate</th><th>Fuel required</th></tr></thead><tbody>{(forecast.daily_projections||[]).map(row=><tr key={row.day}><th>{row.day}</th><td>{n(row.projected_temp_c)} °C</td><td>{n(row.predicted_burn_lh)} L/h</td><td>{n(row.daily_consumption_l,0)} L</td></tr>)}</tbody></table></div></>:<Empty>No fuel forecast available.</Empty>}</section><section className="desk-panel desk-supply-gap"><Package size={22}/><div><h2>Cargo & resupply</h2><p>No shipment, ration, medical inventory or delivery schedule feed is connected to this prototype. Fuel planning is available above; cargo routes can be inspected in the 3D twin.</p></div><button className="desk-link" onClick={onLaunchTwin}>View supply routes<ArrowUpRight size={16}/></button></section></>}
    {section==='analysis'&&<><TelemetryCharts history={history} stationSlug={stationSlug}/><MlDiagnosticsCard telemetry={telemetry} stationSlug={stationSlug}/></>}
    {section==='exercises'&&<IncidentSimulationPanel stationSlug={stationSlug} activeIncident={incident} onTriggerIncident={onTriggerIncident} onRestoreNominal={onRestoreNominal} isLoading={isSimulating}/>}
   </>}
   <footer className="desk-footer"><span>Remote station management prototype · Maitri & Bharati</span><span>Infrastructure / Energy / Logistics / Environment</span></footer>
  </div>
 </div>;
}
